<a href="https://colab.research.google.com/github/MrCristian1/mc-202202-cristian-parada/blob/main/Mctaller14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[1,0,1],
              [3,4,3],
              [4,1,0]])

B = np.array([[2.5],
              [11.5],
              [15]])

# PROCEDIMIENTO
casicero = 1e-15 # Considerar como 0

# Evitar truncamiento en operaciones
A = np.array(A,dtype=float) 

# Matriz aumentada
AB = np.concatenate((A,B),axis=1)
AB0 = np.copy(AB)

# Pivoteo por filas
tamano = np.shape(AB)
w = tamano[0]
ñ = tamano[1]

# Para cada fila en AB
for i in range(0,w-1,1):
    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])
    dmax = np.argmax(columna)
    
    # dmax no está en diagonal
    if (dmax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dmax+i,:]
        AB[dmax+i,:] = temporal
        
AB1 = np.copy(AB)

# eliminacion hacia adelante
for i in range(0,w-1,1):
    pivote = AB[i,i]
    adelante = i + 1
    for k in range(adelante,w,1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
AB2 = np.copy(AB)

# elimina hacia atras
ufila = w-1
ucolumna = ñ-1
for i in range(ufila,0-1,-1):
    pivote = AB[i,i]
    atras = i-1 
    for k in range(atras,0-1,-1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
    # diagonal a unos
    AB[i,:] = AB[i,:]/AB[i,i]
X = np.copy(AB[:,ucolumna])
X = np.transpose([X])


# SALIDA
print('Matriz aumentada:')
print(AB0)
print('Pivoteo parcial por filas')
print(AB1)
print('eliminacion hacia adelante')
print(AB2)
print('eliminación hacia atrás')
print(AB)
print('solución de X: ')
print(X)

Matriz aumentada:
[[ 1.   0.   1.   2.5]
 [ 3.   4.   3.  11.5]
 [ 4.   1.   0.  15. ]]
Pivoteo parcial por filas
[[ 4.   1.   0.  15. ]
 [ 3.   4.   3.  11.5]
 [ 1.   0.   1.   2.5]]
eliminacion hacia adelante
[[ 4.          1.          0.         15.        ]
 [ 0.          3.25        3.          0.25      ]
 [ 0.          0.          1.23076923 -1.23076923]]
eliminación hacia atrás
[[ 1.   0.   0.   3.5]
 [ 0.   1.   0.   1. ]
 [ 0.   0.   1.  -1. ]]
solución de X: 
[[ 3.5]
 [ 1. ]
 [-1. ]]
