<a href="https://colab.research.google.com/github/MrCristian1/mc-202202-cristian-parada/blob/main/Mctaller_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

A = np.array([[3,2,2],
              [3,1,-3],
              [1,0,-2]], dtype=float)

# PROCEDIMIENTO
casicero = 1e-15 # Considerar como 0

# matriz identidad
tamano = np.shape(A)
n = tamano[0]
identidad = np.identity(n)

# Matriz aumentada

AB = np.concatenate((A,identidad),axis=1)
AB0 = np.copy(AB)

# Pivoteo por cada fila
tamano = np.shape(AB)
n = tamano[0]
m = tamano[1]

# Para cada fila en AB
for i in range(0,n-1,1):
    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])
    dondemax = np.argmax(columna)
    
    # dondemax no está en diagonal
    if (dondemax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dondemax+i,:]
        AB[dondemax+i,:] = temporal
AB1 = np.copy(AB)

# eliminacion hacia adelante
for i in range(0,n-1,1):
    pivoteA = AB[i,i]
    adelante = i+1
    for k in range(adelante,n,1):
        factor = AB[k,i]/pivoteA
        AB[k,:] = AB[k,:] - AB[i,:]*factor
AB2 = np.copy(AB)

# elimina hacia atras
ultfila = n-1
ultcolumna = m-1
for i in range(ultfila,0-1,-1):
    pivoteA = AB[i,i]
    atras = i-1 
    for k in range(atras,0-1,-1):
        factor = AB[k,i]/pivoteA
        AB[k,:] = AB[k,:] - AB[i,:]*factor
    # diagonal a unos
    AB[i,:] = AB[i,:]/AB[i,i]

inversa = np.copy(AB[:,n:])

print('Inversa de A: ')
print(inversa)


#--------------------------------------------------------------------------------------------------------------------------------------------------------#
#MATRIZ B

A2 = np.array([[1,2,0,4],
              [2,0,-1,-2],
              [1,1,-1,0],
              [0,4,1,0]], dtype=float)


# PROCEDIMIENTO
casicero = 1e-15 # Considerar como 0

# matriz identidad
tamano = np.shape(A2)
w = tamano[0]
identidad = np.identity(w)

# Matriz aumentada

AB = np.concatenate((A2,identidad),axis=1)
AB0 = np.copy(AB)

# Pivoteo por filas
tamano = np.shape(AB)
w = tamano[0]
ñ = tamano[1]

# Para cada fila en AB
for i in range(0,w-1,1):
    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])
    dmax = np.argmax(columna)
    
    # dmax no está en diagonal
    if (dmax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dmax+i,:]
        AB[dmax+i,:] = temporal
AB1 = np.copy(AB)

# eliminacion hacia adelante
for i in range(0,w-1,1):
    pivoteB = AB[i,i]
    adelante = i+1
    for k in range(adelante,w,1):
        factor = AB[k,i]/pivoteB
        AB[k,:] = AB[k,:] - AB[i,:]*factor
AB2 = np.copy(AB)

# elimina hacia atras
ufila = w-1
ultcolumna = ñ-1
for i in range(ufila,0-1,-1):
    pivoteB = AB[i,i]
    atras = i-1 
    for k in range(atras,0-1,-1):
        factor = AB[k,i]/pivoteB
        AB[k,:] = AB[k,:] - AB[i,:]*factor
    # diagonal a unos
    AB[i,:] = AB[i,:]/AB[i,i]

inversa2 = np.copy(AB[:,w:])

print('Inversa de B: ')
print(inversa2)

Inversa de A: 
[[ 1.  -2.   4. ]
 [-1.5  4.  -7.5]
 [ 0.5 -1.   1.5]]
Inversa de B: 
[[ 3.33333333e-01  6.66666667e-01 -6.66666667e-01 -1.38777878e-17]
 [-6.66666667e-02 -1.33333333e-01  3.33333333e-01  2.00000000e-01]
 [ 2.66666667e-01  5.33333333e-01 -1.33333333e+00  2.00000000e-01]
 [ 2.00000000e-01 -1.00000000e-01  0.00000000e+00 -1.00000000e-01]]
